#!/bin/bash
# init.d script for dynamic dns service (cloudflare.com)

INSTALL_DIR="/opt/cloudflare_client"
CLIENT_PROG="nodejs $INSTALL_DIR/daemon.js"
NAME=cloudflare_client
PIDFILE=/opt/cloudflare_client/pidfile

case "$1" in
    start)
        if [ -f $PIDFILE ]; then
            echo "$NAME is already running!"
            exit;
        fi
        START_DIR=`pwd`
        cd $INSTALL_DIR
        echo "Starting $NAME"
        $CLIENT_PROG > /dev/null & 
        echo $! > $PIDFILE
        cd $START_DIR
    ;;
    stop)
        echo -n "Shutting down $NAME."
        if [ -f $PIDFILE ]; then
            kill -9 `cat $PIDFILE`
            rm -f $PIDFILE
        else
            echo "$NAME is not running...at least there is no $PIDFILE"
        fi
        echo ""
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
